"""Render the error-code reference from the registry.

The codes are data in :mod:`schemapact.exceptions`, and this turns that data
into ``docs/reference/errors.md``. Generating rather than hand-writing means the
documentation cannot claim a code that does not exist, or miss one that does — a
test asserts the file on disk matches what this script produces, so forgetting
to run it fails CI.

    python scripts/generate_error_docs.py           # write the file
    python scripts/generate_error_docs.py --check   # verify it is current
"""

from __future__ import annotations

import argparse
from pathlib import Path

from schemapact.exceptions import REGISTRY

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "reference" / "errors.md"

GROUPS = [
    ("0", "Contract definition", "The contract itself is invalid and cannot be used."),
    ("1", "Structure", "The shape of the data does not match: columns, order, types, row counts."),
    ("2", "Values", "Individual values violate the constraints declared for their feature."),
    ("6", "Compatibility", "A contract change is unsafe in the direction that was checked."),
    ("9", "Integrations", "An optional dependency is missing, or the data cannot be read."),
]

HEADER = """# Error codes

Every failure this library reports carries a stable code. Codes are **permanent**:
once released, one is never reused, renumbered or repurposed, because people
grep logs and configure alerts on them.

Codes are grouped by domain, so the range alone tells you where a failure came
from.

<!-- Generated by scripts/generate_error_docs.py. Do not edit by hand. -->
"""


def render() -> str:
    """Return the full markdown document."""
    lines = [HEADER]

    for prefix, title, description in GROUPS:
        codes = sorted(
            (code for key, code in REGISTRY.items() if key[3] == prefix),
            key=lambda code: code.code,
        )
        if not codes:
            continue

        lines.append(f"\n## MLC{prefix}xx — {title}\n")
        lines.append(f"{description}\n")
        lines.append("| Code | Meaning |")
        lines.append("| --- | --- |")
        lines.extend(f"| `{code.code}` | {code.summary} |" for code in codes)

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Write or verify the generated file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args(argv)

    expected = render()

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT} is missing. Run: python scripts/generate_error_docs.py")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"{OUTPUT} is out of date. Run: python scripts/generate_error_docs.py")
            return 1
        print(f"{OUTPUT.name} is up to date.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT} with {len(REGISTRY)} codes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
